//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenDesing
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipo
    {
        public equipo()
        {
            this.jugadors = new HashSet<jugador>();
        }
    
        public int idEquipo { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<jugador> jugadors { get; set; }
    }
}
