//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenDesing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db7c1be70e4bbf4b92a5aaa49d0069f4c0Entities : DbContext
    {
        public db7c1be70e4bbf4b92a5aaa49d0069f4c0Entities()
            : base("name=db7c1be70e4bbf4b92a5aaa49d0069f4c0Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<equipo> equipoes { get; set; }
        public virtual DbSet<jugador> jugadors { get; set; }
    }
}
